### ISSUE TITLE
[BUG] Download is not working

### ISSUE THREAD

**Issue by EasyTrigger** [linuxserver/docker-ungoogled-chromium#2]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to download anything (with right click or even clicking directly on a download link) nothing happens.
If you try to save an entire webpage (right click on an empty spot -> save as) or if you try to change the default save path in the settings, the browser crashes.
Btw the project is awesome, thanks for everything!

### Expected Behavior

When trying to download anything, a popup window prompting for a save path should appear (maybe the container is missing a gui file manager accessible by the browser?)

### Steps To Reproduce

Start a download in any way possible

-or-

Save an entire webpage

-or-

Change the default save path in the browser settings

### Environment

```markdown
- OS: Debian Bookworm
- How docker service was installed: Docker Compose
```

### CPU architecture

x86-64

### Docker creation

```bash
---
services:
  ungoogled-chromium:
    image: lscr.io/linuxserver/ungoogled-chromium:latest
    container_name: ungoogled-chromium
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=100
      - UMASK=000
      - TZ=Etc/UTC
      - CHROME_CLI=https://www.google.com/
      - TITLE=Chromium
      - CUSTOM_USER=my_user_redacted
      - PASSWORD=my_pass_redacted
      - LC_ALL=en_US.UTF-8
    volumes:
      - /opt/ungoogled-chromium:/config
    ports:
      - 3001:3001
    shm_size: "2gb"
    restart: unless-stopped
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    100
───────────────────────────────────────
[custom-init] No custom files found, skipping...
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

Xvnc KasmVNC 1.2.0 - built Jul 20 2024 19:19:12
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12014000, The X.Org Foundation

[ls.io-init] done.
Obt-Message: Xinerama extension is not present on the server
***** Imlib2 Developer Warning ***** :
        This program is calling the Imlib call:

        imlib_free_image();

        With the parameter:

        image

        being NULL. Please fix your program.
ObRender-Message: Cannot load image "/usr/share/icons/hicolor/scalable/apps/ungoogled-chromium-logo.png" from file "/usr/share/icons/hicolor/scalable/apps/ungoogled-chromium-logo.png"
17
 2024-07-26 16:12:17,475 [INFO] websocket 0: got client connection from 127.0.0.1
 2024-07-26 16:12:17,482 [PRIO] Connections: accepted: @REDACTED_IP::websocket
/usr/bin/wrapped-chromium: line 29:   320 Segmentation fault      (core dumped) ${BIN} --ignore-gpu-blocklist --password-store=basic --simulate-outdated-no-au='Tue, 31 Dec 2099 23:59:59 GMT' --start-maximized --user-data-dir "$@" > /dev/null 2>&1

ERROR: openbox-xdg-autostart requires PyXDG to be installed
```

**Comment by EasyTrigger** [comment]
Update: (issue still NOT resolved)
I was able to add Nautilius to the container using DOCKER_MODS adding theese lines to the compose:

`- DOCKER_MODS=linuxserver/mods:universal-package-install`
`- INSTALL_PACKAGES=nautilius`

Now the browser correctly opens the file manager upon requesting a download or when changing the default download path in the browser settings (so no more crashes) but I am still "unable to normally save anything on the disk" from the browser after confirming the filename and path of the download (after clicking on "Save" nautilius closes and nothing happens).
However, if I select another file alredy on the disk instead of creating a new one, the download starts fine overwriting the old file with the new content.
I hope those informations may be useful to fix this container, I think that an integrated file manager is essential for basic browser usage such as downloading content or importing bookmarks

**Comment by thelamer** [comment]
Yeah that is my bad, rushed a bit on this one, building now please update when that green checkmarks.

**Comment by EasyTrigger** [comment]
> Yeah that is my bad, rushed a bit on this one, building now please update when that green checkmarks.

Love you man, thanks! :) keep it up!
